#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# lint js/ts files
echo 🧿 Running file linter...
npx lint-staged

# format svg
echo 🧿 Running svg formatter...
git diff --diff-filter=ACMRT --cached --name-only -z | grep -z -E "\.svg$" | while IFS= read -r -d '' file
do
    echo "Formatting $file"
    ./node_modules/.bin/svgo -q "$file" --config svgo.config.format.js
    git add "$file"
done

echo ✅ All pre-commit jobs are done
